ansys/pyansys-dev-guide

- doc/source/guidelines/logging.rst
There was a broken link in the section referring users to the Python `logging` documentation at:
`https://docs.python.org/3/library/logging.html`
I also reformatted the paragraphs so you can see it within 80 columns in a text editor.
> Fix broken https link and wrap at 80 columns

- doc/source/guidelines/dev_practices.rst
- doc/source/overview/contributing.rst
Add link from Contributing topic to "Branch Naming Conventions" in Development Practices topic
> Add branch naming conventions link to Contributing

- doc/source/guidelines/dev_practices.rst
- doc/source/overview/basic.rst
- doc/source/overview/contributing.rst
Fixed some formatting issues and TRIED to figure out when to use repository versus project versus library.
> Fix minor doc issues

- doc/source/guidelines/PyMAPDL_WSL_Guide.rst
- doc/source/guidelines/index.rst
Adding Windows Subsystem Linux Guide to Developer guide.
This guide is useful to allow the developers to run native linux code/programs from their windows machines.
> Adding WSL guide

- doc/source/coding_style/best_practices.rst
> Adding security considerations

- README.rst
- doc/source/guidelines/doc_practices.rst
- doc/source/guidelines/index.rst
- doc/source/library_description/index.rst
- doc/source/library_description/template.rst
- doc/source/overview/administration.rst
- doc/source/overview/basic.rst
- doc/source/overview/contributing.rst
- doc/source/overview/index.rst
@akaszynski Locally building a PDF of the dev guide now results in a good ToC.
> doc/edits to fix generation of ToC for PDF of doc

- README.rst
- doc/source/guidelines/doc_practices.rst
I wanted to add a note to the PDF generation section about not having sections in index.rst files. I also made small enhancements to the README.rst file.
> doc/Enhance PDF generation section and README

- doc/source/guidelines/doc_practices.rst
Add a section to define the URL for the documentation page.
Fix #49 .
> Add a section to define the URL for the documentation page.

- .github/workflows/ci-build.yml
Simple fix to point to `doc` rather than `docs` for the deployment step.
> fix doc deployment

- doc/source/conf.py
- doc/source/documentation_style/class_documentation.rst
This PR adds an extra section to the `Class Documentation` page that describes the approach taken for documenting the query and response objects in the grantami-bomanalytics packages.
Since there aren't any appropriate classes in the theme itself, I have included references to the classes in bomanalytics. If we decide this dependency is inappropriate I can come up with some additional example classes that are similar in style to the ones referenced here.
> Include grantami-bomanalytics documentation approach

- doc/source/guidelines/doc_practices.rst
Correct the link toward Google style guide.
Fix #57 .
> Correct the link toward Google style guide.

- doc/source/guidelines/dev_practices.rst
> Fix code snnipet in dev_practices.rst

- doc/source/guidelines/doc_practices.rst
This PR fixes a couple of broken links in the `Documentation practices` page.
> Fix broken links documentation practices

- doc/source/library_description/packaging.rst
Remove guide regarding `setup.py`, and recommend `flit` with `pyproject.toml` instead. For applications (which should have pinned versions instead of loose ones), recommend `poetry`.
> Update packaging guide

- doc/source/library_description/template.rst
> Reorganize Library Overview layout by unifying sections

- doc/source/library_description/library_names.rst
> add library name guidance

- doc/source/library_description/template.rst
Fixes links in [templates section] to properly point to the new renamed
[ansys-templates] repository
[templates section]: https://dev.docs.pyansys.com/library_description/template.html
[ansys-templates]: https://github.com/pyansys/ansys-templates
> Fix ansys-templates links

- doc/source/overview/contributing.rst
@Andy-Grigg 
I moved the Issues entry for openapi-common beneath the five main PyAnsys libraries and then added a link for grantami-bomanalytics. However, I didn't add a link to the Issues page for grantami-bomanalytics-openapi because the Readme for this public library said that direct use was unsupported.
> Add Issues pages for Granta pubilc PyAnsys projects to Contributing page

- doc/source/guidelines/private_packaging.rst
Fix syntax to use private PyPI PAT.
> Fix syntax to use private PyPI PAT.

- doc/source/documentation_style/formatting-tools.rst
- doc/source/documentation_style/index.rst
Partially solves for #64. This is the first of a series of PR to adapt the current "API Documentation Style" to the proposed "Doc Style".
> Add documentation formatting tools section 

- doc/source/guidelines/dev_practices.rst
Suggested fix for #79 
- Remove all mention of merging release/ branches into the main branch
- Split the version update instructions in two parts:
- In release/ branches, it's about removing the `dev0`, or increasing PATCH only
- In the main/ branch, it's about increasing the minor or major version only (keeping .dev0)
- Clarify that the hotfixes should be merged in `main` first, then cherry-picked in any applicable release branch. Remove mentions of "merging" hotfixes branch into "release" branches, this would actually bring a mess from the main branch.
> Update the release process to match the branching model

- doc/source/coding-style/pep8.rst
Adds last code suggestions from #95.
> Fix various typos

- doc/source/doc-style/docstrings.rst
Adds a note to the `docstrings.rst` about how type hints can be rendered in the parameter description instead of the function signature.
> Add info about type hints rendering to the docstrings section

- doc/source/how-to/setting-up.rst
In the "How to" section of the documentation, the link for Git installation on Windows machine was pointing to Python org.
Fix #120  .
> Correct the link to install Git on Windows .

- .pre-commit-config.yaml
- doc/source/conf.py
- doc/source/how-to/code/pyansys_logging.py
This PR imposes "isort" as the main import style checker, similarly to other projects in the PyAnsys ecosystem.
> Use isort instead of import-reorder

- .github/workflows/ci-build.yml
- doc/Makefile
- doc/make.bat
- doc/source/conf.py
- doc/source/how-to/diag/doc_layout.rst
- doc/source/how-to/documenting.rst
Resolves #112 by adding:
- Guidelines on how to set up the TOKEN for doc deployment.
- Using group-tabs for switching between tox and raw doc workflows.
> Update guidelines on doc deploy

- doc/source/how-to/repository-protection.rst
There was a misleading comment raised by @iboyd-ansys saying that internal/private repos did not have such workflow protection rules.
Docs adapted
> Internal repos have no options

- doc/source/conf.py
- doc/source/how-to/diag/doc_layout.rst
- doc/source/how-to/diag/main_branch.rst
- doc/source/how-to/diag/release_branch.rst
- doc/source/packaging/diag/doc_structure_diag.rst
- doc/source/packaging/diag/grpc_structure_diag.rst
- doc/source/packaging/diag/pyansys_namespace_diag.rst
- doc/source/packaging/diag/pyproduct_library_structure_diag.rst
- doc/source/packaging/diag/python_library_diag.rst
- doc/source/packaging/diag/src_structure_diag.rst
- doc/source/packaging/diag/tests_structure_diag.rst
Solves for #143 by forcing a white background in mermaid diagrams.
<div align="center">
</div>
> Force white background in diagrams

- doc/source/doc-style/code/required_conf.py
- doc/source/doc-style/code/required_make.bat
- doc/source/doc-style/code/required_makefile
- doc/source/doc-style/doc-configuration.rst
- doc/source/doc-style/index.rst
- doc/source/packaging/structure.rst
- doc/styles/Vocab/ANSYS/accept.txt
Resolves #150 and includes example `conf.py`, `Makefile` and `make.bat` files.
> Add section about Sphinx required configuration 

- .gitignore
- doc/source/how-to/releasing.rst
Fix twine upload code block.
Fix the TWINE_REPOSITORY_URL for Windows.
Fix #157 
Fix #158
> Improve code sample for downloading from private PyPI.

- doc/source/how-to/documenting.rst
- doc/styles/Vocab/ANSYS/accept.txt
Removes the `get_match_version` function from the multi-version documentation example. This function is already shipped with the latest ansys-sphinx-theme.
> FIX: example to match ansys-sphinx-theme>=0.8

- doc/source/how-to/documenting.rst
Fixes #244 by better explaining the location of the `versions.json` file.
> FIX: description of the versions.json file

- .pre-commit-config.yaml
- doc/source/packaging/code/authors_file.md
- doc/source/packaging/diag/pyproduct_library_structure_diag.rst
- doc/source/packaging/structure.rst
Show the documentation structure in `structure.rst`.
> Show the documentation structure

- doc/source/how-to/releasing.rst
There's still some confusion when reading our private pypi upload. This updates it with additional instructions.
> Add additional private PyPI docs

- doc/source/conf.py
- doc/source/doc-style/docstrings.rst
- doc/source/how-to/documenting.rst
- requirements/requirements_doc.txt
> Fix: update the docs and auto function module with update of theme package.

- doc/source/how-to/documenting.rst
Just saw that we had to update this. All of them have been updated already to this new format except for PyEDB.
> Properly documenting how to access dev docs

- doc/source/getting-started/administration.rst
- doc/source/getting-started/basic.rst
- doc/source/how-to/documenting.rst
- doc/source/how-to/releasing.rst
- doc/source/packaging/code/pyproject_flit_code.rst
- doc/source/packaging/code/pyproject_poetry_code.rst
- doc/source/packaging/code/setup_file_code.rst
Fixes #271 by replacing all the `pyansys.support@ansys.com` email references with `pyansys.core@ansys.com` ones.
> MAINT: replace pyansys.support email with pyansys.core one

- doc/source/conf.py
The documentation for bomanalytics is migrating from https://grantami.docs.pyansys.com/ to https://bomanalytics.grantami.docs.pyansys.com/
https://grantami.docs.pyansys.com/ is still the bomanalytics docs for now, but will become a general documentation page for all Granta MI PyAnsys packages.
> Update bomanalytics url

- doc/source/index.rst
Minor fix to the indentation on the documentation landing page.
> Remove indentation on the landing page

- doc/source/how-to/releasing.rst
> Use twine-username argument for the release-pypi-private action.

- doc/source/getting-started/abbr.rst
- doc/source/getting-started/index.rst
- doc/source/index.rst
- doc/styles/Vocab/ANSYS/accept.txt
This PR adds a "Glossary of abbreviations" page to the "Getting started" section of the developer's guide. To create this glossary, I've skimmed the pages of the developer's guide and the names of public PyAnsys repositories. The intent is to grow this glossary page with abbreviations used in all PyAnsys libraries and then add a reference to this page in the guide in each PyAnsys library.
NOTE: In skimming the developer's guide, I did notice a lot of content that should be modified. I hope to do this in a future PR soon.
> Add a "Glossary of abbreviations" page to the dev guide

- doc/source/doc-style/index.rst
- doc/source/getting-started/basic.rst
- doc/source/how-to/dns-configuration.rst
- doc/source/how-to/documenting.rst
- doc/source/how-to/logging.rst
Hi @jorgepiloto, I have a few questions:
In [doc/source/how-to/dns-configuration.rst](https://github.com/ansys/pyansys-dev-guide/compare/doc/fix-links?expand=1#diff-a1ac5cc6232feb6e57b5695a66998392f172cf00b93462750087516eece4ed4b), should pyansys.com be docs.pyansys.com? 
Here are some other links I couldn't find:
In dev.docs.pyansys.com/getting-started/basic.html:
system-reporting-tool: https://github.com/ansys/system-reporting-tool
- Is this the system reporting tool? [ansys/pyansys-tools-report](https://github.com/ansys/pyansys-tools-report)
In dev.docs.pyansys.com/how-to/documenting.html:
actions.docs.pyansys.com is not a secure website/it says there isn't a GitHub Page site, so I couldn't update these links below
- pyansys/actions/doc-deploy-stable action: …
> Fixed links in rst files

- doc/source/coding-style/formatting-tools.rst
- doc/source/coding-style/required-standard.rst
- doc/source/how-to/packaging.rst
- requirements/requirements_doc.txt
Fix the warnings while building documentation. The warnings indicate that the documentation builder is having difficulty lexing certain code blocks with the "toml" lexer. https://github.com/ansys/pyansys-dev-guide/actions/runs/6940459281/job/18879453184#step:4:3073
> fix: doc build issue with toml code block

- doc/source/coding-style/formatting-tools.rst
- doc/styles/Vocab/ANSYS/accept.txt
- requirements/requirements_doc.txt
Add add-license-headers pre-commit hook to the dev guide
> Add add-license-headers to docs

- doc/source/all-styles.rst
- doc/source/conf.py
- doc/source/index.rst
Combine packaging, coding and documentation styles under Style section
> Combine all styles

- doc/source/how-to/releasing.rst
- f0a6e25 `doc/source/how-to/releasing.rst`: use double quotes for variable expansion (otherwise `INDEX_URL` literally equals `https://$PYANSYS_PYPI_PRIVATE_READ_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/`)
- f002664 `doc/source/how-to/releasing.rst`: fix powershell nested variable
> fix: doc/source/how-to/releasing.rst: fix variables

- doc/source/conf.py
- doc/source/content-writing/content-contrib-setup/essentials.rst
- doc/source/getting-started/basic.rst
- doc/source/how-to/contributing.rst
- doc/source/how-to/testing.rst
- doc/source/links.rst
- doc/source/packaging/structure.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
As some repositories are enforcing the [conventional-commit standards](https://github.com/commitizen/conventional-commit-types/blob/master/index.json), this PR is to add a mention about it within our documentation.
> docs: adding a `commit-naming conventions` section and updating `links.rst` and `basics.rst`

- doc/source/how-to/documenting.rst
Documentation can be generated without running examples. This PR updates required instructions.
> DOC: Add documentation  for html-noplot

- doc/source/how-to/contributing.rst
- doc/source/how-to/repository-protection.rst
This pull-request documents how to use GitHub rulesets for enforcing branch names and tags.
> doc: rulesets for branch and tag naming

- doc/source/packaging/code/contributors_file.md
Removed "or owner" from title and made the individual contributors generic. 
See [this PR](https://github.com/ansys/pre-commit-hooks/pull/233)
> doc: adjust contributors file wording

- doc/source/coding-style/formatting-tools.rst
> feat: adding pre-commit.ci config

- doc/source/how-to/repository-protection.rst
As title says - we use this prefix in many of our repos and actions
PS: I know "maint" is not part of the standard but this is for branch naming conventions (not for commits per se). I think we should consider accepting it since we have used it for a long time and it englobes several miscellaneous operations IMO
> fix: allow for maint branches

- doc/source/how-to/releasing.rst
In the context of git, **stage** means to add a changeset to be committed, **stash** means to save the changes locally and remove them from the working set.
In both cases here it should be **stage**
> Minor Text Fix

- doc/source/_rulesets/main.json
- doc/source/_rulesets/tag-create.json
- doc/source/_rulesets/tag-delete.json
- doc/source/how-to/repository-protection.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
- requirements/requirements_doc.txt
> doc: Include ruleset files in documentation

- doc/source/_rulesets/branch_naming.json
- doc/source/how-to/contributing.rst
- doc/source/how-to/repository-protection.rst
Fixes issues raised in https://github.com/ansys/pyansys-dev-guide/pull/528#issuecomment-2485834790
> fix: Branch name protection fixes

- .github/workflows/nightly-build.yml
Expanding on the title, the directories being targeted by the action uploading the html and pdf documentation is incorrect. Corrected this (see the contents of tox.ini/Makefile).
> fix: correct artifact upload target directories for html and pdf documentation

- doc/source/conf.py
- doc/source/getting-started/administration.rst
- doc/source/links.rst
This pull-request updates the form for requesting an open-source release. The form is only accessible by ANSYS, Inc. employees.
> fix: link to OSS request form

- doc/source/how-to/packaging.rst
As title says. Coming from dev meeting feedback raised by @greschd
> feat: clarification on using dependency groups and extras

- doc/source/coding-style/formatting-tools.rst
- doc/source/coding-style/required-standard.rst
- doc/source/content-writing/content-how-tos/create-PR.rst
- doc/source/content-writing/content-how-tos/resolve-issues-causing-check-failures.rst
- doc/source/links.rst
This PR implements the changes discussed in #589, i.e. replacing the sections in the code style tools documentation presenting Black, isort and Flake8 for code formatting and linting by a brief overview on how to perform these tasks with Ruff. Other parts of the documentation are also updated where necessary to take this change into account.
Ruff is introduced as a faster alternative to the previously used tools, combining in one common interface the features of interest for formatting and linting. A few key facts about Ruff are cited, a minimum Ruff setup for PyAnsys projects is provided and a recommended approach to add rules incrementally when migrating a project towards using Ruff is suggested. 
As mentioned in #589, it should be noted that blacken-docs, used for formatting Python …
> docs: Adding section on Ruff in code style tools page

- .flake8
- .github/labeler.yml
- .pre-commit-config.yaml
- doc/source/doc-style/code/sample_func.py
- doc/source/how-to/code/pyansys_logging.py
- doc/source/how-to/code/test_pyansys_logging.py
- examples/pyvista_example.py
- ruff.toml
This PR implements the change discussed in #593, i.e. migrating the pyansys-dev-guide to Ruff.
The specific configs for Black, isort and flake8 are removed and the .pre-commit-config.yaml file is updated accordingly, while a ruff.toml file defining the rules used by Ruff for linting and formatting is introduced.
Python files fixed by Ruff are updated.
Since the project does not currently contain a pyproject.toml file, it was decided not to define one for the purpose of holding the Ruff configuration, but instead to specify it in a ruff.toml file placed at the root of the project. The introduction of a pyproject.toml file is considered to be beyond the scope of this PR, which is the motivation for this choice.
Should a pyproject.toml file be created in the future, the content of the …
> chore: use ruff with ruff.toml file

- doc/source/how-to/documenting.rst
- doc/source/links.rst
> feat: facilitating example contribution

- doc/source/how-to/vulnerabilities.rst
- doc/source/links.rst
This PR aims to provide guidance for common vulnerabilities.
> docs: addressing common vulnerabilities
