README.rst
=> Added link to web in Readme

doc/source/guidelines/private_packaging.rst
Thanks @cdan6 for pointing this out.
=> Fix minor typo in private packaging

.pre-commit-config.yaml, doc/source/guidelines/doc_practices.rst
Document our documentation CI.
=> Add documentation CI

configure_venv.bat, configure_venv.sh
=> Requirement_style is not required anymore while configuring virtual environment

doc/source/how-to/releasing.rst
=> Add contact info to get a dedicated token.

doc/source/overview/basic.rst
I'm also going to try to do the same PyPIM addition and alphabetic reordering to the ReadMe page for the PyAnsys organization, if I have write permissions.
=> Add PyPIM to released libraries and reorder alphabetically

.github/dependabot.yml
A small bug introduced in #115.
=> Fix dependencies location in dependabot

.github/workflows/ci-build.yml
Update the workflow in dev guide for automatic rendering and deploying after every push.
=> Update Deploy to gh-pages in Workflow.

doc/source/how-to/code/build.yml, doc/source/how-to/code/docs.yml, doc/source/how-to/code/release.yml, doc/source/how-to/code/style.yml, doc/source/how-to/code/tests.yml, doc/source/how-to/continuous-integration.rst
=> Disabling CI in concurrent workflows

.github/labeler.yml, .github/labels.yml, .github/workflows/labeler.yml
This PR implements a label syncer and the autolabeler of pull-requests.
=> Implement automatic labeler

doc/source/how-to/index.rst, doc/source/how-to/repository-protection.rst
=> Include repository protection rules

doc/source/how-to/documenting.rst, doc/source/packaging/build-systems.rst, doc/source/packaging/templates.rst
Related with https://github.com/ansys/ansys-templates/issues/115.
=> Update links to ansys/ansys-templates

doc/source/how-to/code/release.yml, doc/source/how-to/releasing.rst
=> Improve instructions on private PyPI

doc/source/doc-style/doc-configuration.rst, doc/source/how-to/setting-up.rst
Solves #91 by adding some information regarding how to deal with EOL in VCS.
=> Add EOL policy

doc/source/coding-style/deprecation.rst, doc/source/coding-style/formatting-tools.rst, doc/source/doc-style/docstrings.rst, doc/source/doc-style/formatting-tools.rst
Fix small details about the imports.
=> General enhancements.

README.rst, doc/source/doc-style/doc-configuration.rst
Edit the README to add a missing space between sentences and reduce the wordiness of the last paragraph.
=> Edit README and Sphinx config topic

doc/source/how-to/compatibility.rst, doc/source/how-to/index.rst
=> Ansys product compatibility version documentation

doc/source/_static/css/ansys.css, doc/source/coding-style/formatting-tools.rst, doc/source/coding-style/pep8.rst, doc/source/conf.py, doc/source/how-to/continuous-integration.rst, doc/source/how-to/documenting.rst, doc/source/how-to/packaging.rst, doc/source/how-to/releasing.rst, doc/source/how-to/setting-up.rst, doc/source/how-to/testing.rst, doc/source/packaging/code/pyproject_code.rst, requirements/requirements_doc.txt
Fix #182 . Adding here a css file for sphinx design, and can add these feature in ``ansys-sphinx-theme`` later.
=> Replace tab with sphinx design

.github/workflows/ci-build.yml, .github/workflows/nightly-build.yml
=> Fix the display issue for the virtual server environment.

.github/workflows/ci-build.yml, .github/workflows/nightly-build.yml
Add virtual server env display with other dependencies
Make pdf build with proper command in nightly docs
=> Modify pdf build on nighty-doc-build

doc/source/packaging/templates.rst
=> Broken links for ansys-templates

doc/source/how-to/continuous-integration.rst, doc/source/how-to/documenting.rst
This pull-request adds some improvements to the section on how to enabling multi-version documentation.
=> DOC: improve multi-version docs

doc/source/how-to/documenting.rst
This pull request adds the `DOCUMENTATION_CNAME` environment variable in the YML files to clarify its usage with the multi-version docs.
=> FIX: usage of env with multi-version

doc/Makefile, doc/source/conf.py, doc/source/how-to/contributing.rst, doc/source/how-to/documenting.rst
Resolve #222 by adding links to be able to directly join the PyAnsys organization.
=> update the github links

.github/workflows/ci-build.yml, doc/source/conf.py, doc/source/how-to/contributing.rst
Add edit button to the developer documentation.
Also, discovered we were deploying documentation within PRs. This PR modifies our deployment step to deploy only on `main`.
=> add edit button

doc/source/coding-style/pep8.rst
=> Change use/avoid order in tabs

.github/workflows/ci-build.yml, doc/source/conf.py
=> Broken link

doc/source/how-to/code/build.yml, doc/source/how-to/code/docs.yml, doc/source/how-to/code/release.yml, doc/source/how-to/code/style.yml, doc/source/how-to/code/tests.yml, doc/source/how-to/documenting.rst, doc/source/how-to/supporting-python-versions.rst
This pull-request updates the version of the pyansys/actions used in the examples.
=> DOC: update examples versions

doc/source/how-to/packaging.rst
This PR removes two instances of `The` in the middle of sentences
=> Remove two odd capitals

doc/source/how-to/releasing.rst
=> Update our Private PyPI instructions for Windows

doc/source/how-to/releasing.rst
Should not use `<PAT>` but rather `__token__` for username for twine.
=> Update upload instructions

doc/source/how-to/setting-up.rst
This is mostly to demo us changing the docs.
=> Quick patch for the dev guide

.github/workflows/ci_cd.yml
Fixes the issues raised in https://github.com/pyansys/dev-guide/actions/runs/4312150328.
=> FIX: github deployment

.github/workflows/ci_cd.yml
Continuation of #273. I forgot to download the artifacts before deploying them.
=> CI: upload and download artifacts for publishing

doc/source/how-to/releasing.rst
Pinging @kellymore for her review.
Badly needed based on user interaction.
=> Add one liner for uploading and downloading from our private PyPI

doc/source/getting-started/administration.rst
https://dev.docs.pyansys.com/getting-started/administration.html has unnecessary indentation in the panels and it's causing the text to be rendered as "quote blocks." Screenshot:
=> Fix indentation for in Project approval

doc/source/how-to/releasing.rst
Panel text is over-indentation.
=> Update indentation on releasing

.github/workflows/ci_cd.yml, doc/source/how-to/documenting.rst
Made edits to ensure that the reader understood where to find the drop-down button within the doc for a PyAnsys library.
=> Make minor changes to info on switching doc versions

doc/source/how-to/setting-up.rst
=> feat: adding git tutorial

doc/source/getting-started/administration.rst
As title says. Pinging involved parties for review
@jorgepiloto @MaxJPRey @ChrisHarrold
=> feat: add information in regards to release forms

doc/make_pdf.bat, doc/source/getting-started/administration.rst, doc/source/packaging/code/authors_code.rst, doc/source/packaging/code/contributors_file.md, doc/source/packaging/diag/pyproduct_library_structure_diag.rst, doc/source/packaging/structure.rst
=> feat: docs on AUTHORS/CONTRIBUTORS files

doc/source/how-to/code/build.yml, doc/source/how-to/code/docs.yml, doc/source/how-to/code/release.yml, doc/source/how-to/code/style.yml, doc/source/how-to/code/tests.yml, doc/source/how-to/documenting.rst, doc/source/how-to/releasing.rst, doc/source/how-to/supporting-python-versions.rst, doc/styles/Vocab/ANSYS/accept.txt, requirements/requirements_doc.txt
=> docs: add document for usage of pymeilisearch actions

.github/workflows/ci_cd.yml, doc/source/conf.py, requirements/requirements_doc.txt
Add the theme options and workflow to configure pymeilisearch
=> feat: add the indexing workflow to configure pymeilisearch

README.rst, doc/source/coding-style/pep8.rst, doc/source/conf.py, doc/source/how-to/compatibility.rst
As title says - linkcheck was failing
=> fix: links

.github/dependabot.yml
=> maint: weekly dependabot updates

.github/workflows/ci_cd.yml, doc/.vale.ini, doc/source/conf.py, doc/source/getting-started/administration.rst
Previous request form required to fill a document.
The new approach is to fill an issue at:
https://github.com/ansys-internal/oss-approval-tracklist/issues
=> bugfix: change code release request

doc/source/how-to/index.rst
Add cards to simplify how-to page
=> Doc: Modify how-to page

doc/source/how-to/code/release.yml
=> fix: change gitub to github

.github/workflows/ci_cd.yml, doc/source/content-writing/content-how-tos/work-around-Vale.rst
=> docs: update ansys/actions version for doc-style

doc/source/index.rst
As per the https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179521916
=> fix: alignment of multiples cards

doc/source/getting-started/componentization.rst
I was reading through the docs and encountered a typo. So, I fixed it.
=> DOC: Fixing typo

AUTHORS, CONTRIBUTING.md, CONTRIBUTORS.md
As the title.
Close #510
Close #509
=> fix: files

.github/workflows/ci_cd.yml, .github/workflows/nightly-build.yml, doc/source/coding-style/code/tox-flit.rst, doc/source/coding-style/code/tox-poetry.rst, doc/source/how-to/code/build.yml, doc/source/how-to/code/docs.yml, doc/source/how-to/code/release.yml, doc/source/how-to/code/style.yml, doc/source/how-to/code/tests.yml, doc/source/how-to/continuous-integration.rst, doc/source/how-to/releasing.rst, doc/source/how-to/supporting-python-versions.rst, requirements/requirements_doc.txt
=> feat: using Python 3.13

doc/source/getting-started/administration.rst
=> docs: add disclaimer for CTO approver

.github/workflows/ci_cd.yml, .github/workflows/nightly-build.yml
As title says - not ideal but will unblock the CI/CD
=> ci: use ubuntu-22.04 on doc build

.pre-commit-config.yaml, LICENSE, examples/pyvista_example.py
=> chore: adding pre-commit hook

LICENSE
=> chore: update License
